export const variablesEnum = {
    username: "user",
    password: "5d2b4096-3a04-4271-9982-baa9934dd746",
    urlBase : "http://localhost:9090",
    urlSiesa : "/api/siesa",
    urlLevis : "/api/levis",
    urlOfima : "/api/ofima",
    urlBodegas: "/bodegas",
    urlUbicaciones: "/bodegas/ubicaciones",
    urlListaPrecios: "/listaPrecios",
    urlItemsById: "/items/itemsById",
    urlRemisionesConsecutivo: "/remisiones/remisionByConsecutivo",
    urlItemsByCodigoBarra: "/items/itemsByCodigoBarra",
    urlQuincenas: "/Bonificaciones/getQuincenas",
    urlCertificadosActivos: "/certificados/activo",
    urlCertificadosRetirado: "/certificados/retirado",
    urlHistorialContratosRetirado: "/certificados/retirados",
    urlContratosProximoVencer: "/certificados/ContratosProximoVencer",
    urlContratosProximoVencerByCedula: "/certificados/ContratosProximoVencerByCedula",
    urlCentroCostos: "/centroCostos",
}