export const variablesEnum = {
    username: "user",
    password: "e380399c-610e-41cf-9744-12e8e6e07c83",
    urlBase : "http://localhost:9090",
    urlSiesa : "/api/siesa",
    urlLevis : "/api/levis",
    urlOfima : "/api/ofima",
    urlBodegas: "/bodegas",
    urlUbicaciones: "/bodegas/ubicaciones",
    urlListaPrecios: "/listaPrecios",
    urlItemsById: "/items/itemsById",
    urlRemisionesConsecutivo: "/remisiones/remisionByConsecutivo",
    urlItemsByCodigoBarra: "/items/itemsByCodigoBarra",
    urlQuincenas: "/Bonificaciones/getQuincenas",
    urlBonificaciones: "/Bonificaciones/addBonificaciones",
    urlEmpleadosActivos: "/empleados/activo",
    urlAllEmpleadosActivos: "/empleados/allActivos",
    urlEmpleadoRetirado: "/empleados/retirado",
    urlEmpleadosRetirados: "/empleados/retirados",
    urlEmpleadosProximoVencer: "/empleados/ContratosProximoVencer",
    urlEmpleadosProximoVencerByCedula: "/empleados/ContratosProximoVencerByCedula",
    urlCentroCostos: "/centroCostos",
    urlTipoInventarios: "/tipoInventarios",
    urlActivosFijos: "/activosFijos",
    urlTasaCambio: "/tasaCambio",
}