export const variablesEnum = {
    username: "user",
    password: "bf529f8c-0388-4556-9627-2eefafd4493a",
    urlBase : "http://localhost:9090",
    urlSiesa : "/api/siesa",
    urlLevis : "/api/levis",
    urlOfima : "/api/ofima",
    urlBodegas: "/bodegas",
    urlUbicaciones: "/bodegas/ubicaciones",
    urlListaPrecios: "/listaPrecios",
    urlItemsById: "/items/itemsById",
    urlItemsByIds: "/items/itemsByIds",
    urlItemById: "/items/itemById",
    urlRemisionesConsecutivo: "/remisiones/remisionByConsecutivo",
    urlItemsByCodigoBarra: "/items/itemsByCodigoBarra",
    urlQuincenas: "/Bonificaciones/getQuincenas",
    urlGetBonificaciones: "/Bonificaciones/getBonificaciones",
    urlAddBonificaciones: "/Bonificaciones/addBonificaciones",
    urlUploadBonificacionesToOfima: "/Bonificaciones/uploadBonificaciones",
    urlEmpleadosActivos: "/empleados/activo",
    urlAllEmpleadosActivos: "/empleados/allActivos",
    urlEmpleadoRetirado: "/empleados/retirado",
    urlEmpleadosRetirados: "/empleados/retirados",
    urlEmpleadosProximoVencer: "/empleados/ContratosProximoVencer",
    urlEmpleadosProximoVencerByCedula: "/empleados/ContratosProximoVencerByCedula",
    urlCentroCostos: "/centroCostos",
    urlTipoInventarios: "/tipoInventarios",
    urlActivosFijos: "/activosFijos",
    urlTasaCambio: "/tasaCambio",
}