import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import {NavigationBar} from "@/components/common/NavBar";
import { LogOutIcon } from "lucide-react"

import Image from 'next/image'
import '@/../public/images/Levis-Logo.png'

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Levi's Colombia Intranet",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="h-screen overflow-y-scroll">
      <header>
        <nav className="relative flex items-center justify-center h-20 px-10 border-b-4 border-red-500">
            <Image className="absolute left-20" src="/images/Levis-Logo.png" width={100} height={100} alt="" />
          <NavigationBar/>
            <div className="hover:text-red-500 absolute gap-x-2 right-20 flex items-center font-bold justify-center h-full w-56">
                <div>
                    <h3>Felipe Sarmiento </h3>
                    <h4 className="text-[12px] text-right text-gray-500">Admin</h4>
                </div>
                <LogOutIcon/>
            </div>
        </nav>
      </header>
      <main className="flex min-h-[calc(100vh_-_80px)] ">
          { children }
      </main>
      </body>
    </html>
  );
}
